// modes.js — Mode presets, CONTEXT.md generation, and budget estimation

const fs   = require('fs');
const path = require('path');
const { ROOT, DATA_DIR, CONTEXT_MD, MODES_FILE } = require('./config');
const { readData, writeData, appendSession } = require('./backup');
const { scanSkills, invalidateSkillCache } = require('./skills');
const { estimateTokens } = require('../compiler');

const DEFAULT_MODES = {
  modes: [
    {
      id: 'all', label: 'All On', icon: 'unlock',
      desc: 'Activate all discovered skills for maximum capability.',
      skills: []
    },
    {
      id: 'coding', label: 'Heavy Coding', icon: 'code',
      desc: 'Optimized for complex refactoring and library development.',
      skills: ['example-skill']
    },
    {
      id: 'minimal', label: 'Lean Mode', icon: 'shield',
      desc: 'Minimal context for faster inference and lower token usage.',
      skills: []
    }
  ]
};

function getModes() {
  try { return JSON.parse(fs.readFileSync(MODES_FILE, 'utf8')); }
  catch { return DEFAULT_MODES; }
}

function regenerateCONTEXTmd() {
  const SKILL_MAP = scanSkills(true);
  const states = readData('skill-states.json') || {};
  const stateMap = states.states || states;
  const activeSkills = Object.entries(SKILL_MAP).filter(([id]) => stateMap[id] !== false);
  const skillTable = activeSkills.map(([,s]) => {
    const relPath = path.relative(ROOT, s.path).replace(/\\/g, '/');
    return `| ${s.cat.padEnd(28)} | ${relPath} |`;
  }).join('\n');
  const activeCount = activeSkills.length;
  const total = Object.keys(SKILL_MAP).length;
  const now = new Date().toISOString().split('T')[0];
  const content = `# System Context
> Auto-loaded by AI Agent. Last updated: ${now}.
> Active skills: ${activeCount}/${total}. Regenerated by Context Engine.

---

## Data Files (read at session start)
| File | Purpose |
|------|---------|
| data/memory.json | Built memory |
| data/rules.json | Operational rules |
| data/skill-states.json| Which skills are active/inactive |

---

## Active Skills (${activeCount}/${total})
Before any task, check if a matching skill is active, then read its SKILL.md.

| Task type                     | Skill file |
|-------------------------------|------------|
${skillTable}
`;
  fs.writeFileSync(CONTEXT_MD, content, 'utf8');
  return { activeCount, total };
}

function applyMode(modeId) {
  const SKILL_MAP = scanSkills();
  const modesData = getModes();
  const mode = modesData.modes.find(m => m.id === modeId);
  if (!mode) return null;
  const backup = readData('skill-states.json');
  const states = backup || {};
  const stateMap = { ...(states.states || {}) };

  Object.keys(SKILL_MAP).forEach(id => { stateMap[id] = false; });

  if (mode.id === 'all') {
    Object.keys(SKILL_MAP).forEach(id => { stateMap[id] = true; });
  } else {
    mode.skills.forEach(id => { if(SKILL_MAP[id]) stateMap[id] = true; });
  }

  const newStates = { version: '1.0', last_updated: new Date().toISOString().split('T')[0], states: stateMap };
  try {
    writeData('skill-states.json', newStates);
    const regen = regenerateCONTEXTmd();
    appendSession({ type: 'mode_applied', mode: modeId, skills: Object.keys(stateMap).filter(k => stateMap[k]) });
    return newStates;
  } catch (e) {
    // Rollback both state file and CONTEXT.md on failure
    if (backup) {
      writeData('skill-states.json', backup);
      try { regenerateCONTEXTmd(); } catch {}
    }
    throw e;
  }
}

function estimateContextBudget() {
  try {
    const contextMd  = fs.existsSync(CONTEXT_MD) ? fs.readFileSync(CONTEXT_MD, 'utf8') : '';
    const memText   = JSON.stringify(readData('memory.json') || '');
    const rulesText = JSON.stringify(readData('rules.json') || '');
    const contextTokens = estimateTokens(contextMd);
    const memoryTokens  = estimateTokens(memText);
    const rulesTokens   = estimateTokens(rulesText);
    const totalTokens   = contextTokens + memoryTokens + rulesTokens;
    return {
      contextMdChars: contextMd.length, memoryChars: memText.length,
      rulesChars: rulesText.length, totalChars: contextMd.length + memText.length + rulesText.length,
      estimatedTokens: totalTokens, budgetPercent: Math.round((totalTokens / 200000) * 100),
      contextMdLines: contextMd.split('\n').length,
      breakdown: {
        context: { chars: contextMd.length, tokens: contextTokens },
        memory:  { chars: memText.length, tokens: memoryTokens },
        rules:   { chars: rulesText.length, tokens: rulesTokens },
      }
    };
  } catch(e) { return { error: e.message }; }
}

module.exports = { DEFAULT_MODES, getModes, regenerateCONTEXTmd, applyMode, estimateContextBudget };
